worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    upstream element_web {
        server matrix_element:80;
    }

    upstream synapse {
        server matrix_synapse:8008;
    }

    # 0) insomniafest.ru must have the following two well-known endpoints for Matrix clients to discover the homeserver and federation server:
    # location = /.well-known/matrix/client {
    #     default_type application/json;
    #     return 200 '{"m.homeserver":{"base_url":"https://synapse.insomniafest.ru"}}';
    # }

    # location = /.well-known/matrix/server {
    #     default_type application/json;
    #     return 200 '{"m.server":"synapse.insomniafest.ru:443"}';
    # }

    # 1) Element Web: chat.insomniafest.ru
    server {
        listen 80;
        server_name chat.insomniafest.ru;

        location / {
            proxy_pass http://element_web/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Synapse Admin
        location /admin/ {
            proxy_pass http://matrix_admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            try_files $uri /index.html;
        }

        location /help {
            alias /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }
    }

    # 2) Synapse API/backend: synapse.insomniafest.ru
    server {
        listen 80;
        server_name synapse.insomniafest.ru;

        location ^~ /_matrix/ {
            proxy_pass http://synapse;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            client_max_body_size 50M;
        }

        location ^~ /_synapse/ {
            proxy_pass http://synapse;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_http_version 1.1;
            client_max_body_size 50M;
        }

        location / {
            return 404;
        }
    }
}
